-- Copyright (c) 2026 WSO2 LLC. (https://www.wso2.com).
--
-- WSO2 LLC. licenses this file to you under the Apache License,
-- Version 2.0 (the "License"); you may not use this file except
-- in compliance with the License.
-- You may obtain a copy of the License at
--
-- http://www.apache.org/licenses/LICENSE-2.0
--
-- Unless required by applicable law or agreed to in writing,
-- software distributed under the License is distributed on an
-- "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
-- KIND, either express or implied.  See the License for the
-- specific language governing permissions and limitations
-- under the License.

-- 000088_incident_correlation_id guessed VARCHAR(255). ServiceNow's real
-- incident.correlation_id field (its sys_dictionary entry, on the task
-- table) is max_length 100 -- narrow to match so this column can never
-- silently accept a value ServiceNow itself would reject.
ALTER TABLE incident ALTER COLUMN correlation_id TYPE VARCHAR(100);
